### PR TITLE
Work on barber queue that should update every time we the barber releases a client

### PR DESCRIPTION
**Pull request by linakherchi**

### CODE REVIEW

**Comment by carlosaicrag** [comment]
One Issue I found so far is that when i go to queue/11 for the first time I error out. It's only upon refresh that I actually get to the page

**Comment by carlosaicrag** [comment]
Also, what does "chez" next to the barbers name suppose to be.  I looked up the french definition it looks like it is "in"? lol is that correct?

**Comment by carlosaicrag** [comment]
Another thing I would add is a fail-safe when we want to release a client.  something like "are you sure that you want to release?" Just in case that a barber accidentally clicks the release button. We should also introduce this when a barber is signing out.

**Comment by carlosaicrag** [comment]
We also make sure that the queue updates when we release a client.  For example, if bob pancake is getting a haircut and Joe Twinkletoes is up next we want Joe twinkle toes to show up next when the barber clicks take a client

**Comment by carlosaicrag** [comment]
I would want to include a picture of the haircut that the barber is giving just so that he can have a reference and talk to the client on whether that was correct or not.

**Comment by carlosaicrag** [comment]
Overall, I think the styling is great, and the functionality is great but it needs just a little improvement on the functionality of the page per the comments I made above. Later on, we might want to revamp the styling just to give it a little more color and flair, but for now, this is perfect as an MVP.  We can talk a little more about how we can give the overall site a better design so that users can be drawn to it.  It's probably going to come down to the small details but we can worry about that a little later.

**Comment by linakherchi** [comment]
> I would want to include a picture of the haircut that the barber is giving just so that he can have a reference and talk to the client on whether that was correct or not. Maybe have some sort of modal come up when we clicks that image ? we can discuss this further

**Pull request merged**
